spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/AutoApi?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: jinkai1987
      initialize: true
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.autotest.mybatis

server:
  port: 8080
  content-path: /varExpressService